import { ArrowRight, Plus, Trash, UsersThree, X } from "@phosphor-icons/react";
import { useCallback, useEffect, useRef, useState } from "react";
import { getUserSkills, saveUserSkills } from "../api";
import { useDialogFocus } from "../hooks/useDialogFocus";
import type { UserSkill } from "../types";

type Props = { open: boolean; onClose: () => void; onSaved: (message: string) => void; demoPrompt?: boolean };
const starter = (): UserSkill => ({ id: crypto.randomUUID(), name: "团队会议分析约定", enabled: true, content: "# 团队会议分析约定\n\n## 成员称呼\n\n在这里写正式姓名、昵称和常用称呼的对应关系。\n\n## 项目术语\n\n在这里写缩写、内部术语和业务含义。\n\n## 优先级习惯\n\n用自然语言说明何时应判定高、中或低优先级；如果信号冲突，请要求人工澄清。\n\n## 任务整理要求\n\n说明交付物、验收标准或团队特有的整理习惯。" });
const getMessage = (error: unknown) => error instanceof Error ? error.message : "用户 Skill 请求没有完成。";

export function UserSkillsPanel({ open, onClose, onSaved, demoPrompt = false }: Props) {
  const panelRef = useRef<HTMLElement>(null); const [skills, setSkills] = useState<UserSkill[]>([]); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [demoNotice, setDemoNotice] = useState(demoPrompt); const close = useCallback(onClose, [onClose]);
  useDialogFocus(open, panelRef, close);
  useEffect(() => { if (!open) return; setLoading(true); setError(""); setDemoNotice(demoPrompt); getUserSkills().then((data) => setSkills(data.skills)).catch((caught) => setError(getMessage(caught))).finally(() => setLoading(false)); }, [open, demoPrompt]);
  if (!open) return null;
  const update = (index: number, patch: Partial<UserSkill>) => setSkills((current) => current.map((skill, skillIndex) => skillIndex === index ? { ...skill, ...patch } : skill));
  const loadDemo = () => { setSkills([{ id: crypto.randomUUID(), name: "故障复盘与成员称呼", enabled: true, content: "# 故障复盘与成员称呼\n\n## 成员称呼\n\n- 老张、张哥和小张都指张三，他负责研发和基础设施。\n\n## 项目术语\n\n- S1 表示生产环境一级故障。\n- 灰度表示先覆盖校内用户，再逐步扩大范围。\n\n## 优先级习惯\n\n- S1 故障通常是高优先级。\n- 一般故障复盘通常是低优先级。\n- 如果同一任务同时符合相互冲突的规则，不要自行决定，要向用户澄清。\n\n## 任务整理要求\n\n- 故障复盘要包含根因、触发条件和防止复发的检查项。" }]); setDemoNotice(false); };
  const save = async () => { setSaving(true); setError(""); try { await saveUserSkills({ skills: skills.filter((skill) => skill.name.trim() && skill.content.trim()).map((skill) => ({ ...skill, name: skill.name.trim(), content: skill.content.trim() })) }); onSaved("用户 Skill 已保存，下一次分析会使用启用的 Markdown"); close(); } catch (caught) { setError(getMessage(caught)); } finally { setSaving(false); } };
  return <div className="config-backdrop context-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><section ref={panelRef} className="config-panel context-panel liquid-glass" role="dialog" aria-modal="true" aria-labelledby="skills-title" aria-describedby="skills-description"><header className="config-head"><div><p>USER SKILLS · MARKDOWN</p><h2 id="skills-title">用你的语言定义<em>模型参考。</em></h2></div><button type="button" onClick={close} aria-label="关闭用户 Skill 设置" title="关闭"><X /></button></header><p className="context-intro" id="skills-description"><UsersThree /> 每个 Skill 都是一份独立 Markdown 文档。正文由你自由定义，系统只管理名称、启用状态和版本文件；它不能改变审批、安全或工具权限。</p>{demoNotice && <div className="context-demo-prompt"><p>这两份测试纪要都需要成员别名与优先级规则。当前配置不会自动改变。</p><button type="button" onClick={loadDemo}>载入测试 Skill（未保存）</button></div>}{loading ? <div className="context-loading" role="status"><i className="loader" /> 正在读取用户 Skill…</div> : <><div className="skill-list">{skills.map((skill, index) => <article className="skill-editor" key={skill.id}><header><label><span>Markdown 文件名</span><input value={skill.name} onChange={(event) => update(index, { name: event.target.value })} /></label><label className="skill-toggle"><span>启用</span><input type="checkbox" checked={skill.enabled} onChange={(event) => update(index, { enabled: event.target.checked })} /></label><button className="icon-button" type="button" onClick={() => setSkills((current) => current.filter((_, itemIndex) => itemIndex !== index))} aria-label={`删除 ${skill.name || "用户 Skill"}`}><Trash /></button></header><label><span className="visually-hidden">{skill.name} Markdown 正文</span><textarea value={skill.content} onChange={(event) => update(index, { content: event.target.value })} spellCheck={false} rows={14} /></label><footer><code>scope: meeting-analysis · markdown</code><span>{skill.content.length.toLocaleString()} 字符</span></footer></article>)}</div>{!skills.length && <p className="context-empty">还没有用户 Skill。添加一份 Markdown，把团队知识和判断习惯写给模型。</p>}<button className="add-skill" type="button" onClick={() => setSkills((current) => [...current, starter()])}><Plus /> 添加 Markdown Skill</button>{error && <p className="error-message" role="alert">{error}</p>}<div className="config-feedback" aria-live="polite">系统 Prompt Skill、审批与安全规则不会被用户 Skill 覆盖。</div><footer className="config-actions context-actions"><button type="button" onClick={close}>取消</button><button className="save-config" type="button" onClick={() => void save()} disabled={saving}>{saving ? "正在保存…" : "保存用户 Skill"}<ArrowRight /></button></footer></>}</section></div>;
}
